### PR TITLE
Chapters 3, 4 and 6 updated to Roo 1.2.0 [rev 9ba1451]

### PR DESCRIPTION
**Pull request by jbbarquero**
For the chapters 3, 4 and 6:
- Changed the @RooEntity annotation to @RooJpaActiveRecord since the former no longer exists from Roo 1.2.
- Imported the @RooJpaActiveRecord annotation in the Entity classes when necessary (Ctrl/Cmd+Shift+o in STS, Roo doesn't seem to create the import line sometimes)
- Deleted the _Roo_Entity.aj when necessary (Roo doesn't seem to do that for now)
- Executed 'perform tests' until 'BUILD SUCCESS'
- Created an empty file in src/test/resources for giving GIT an entire maven structure
- Excluded the .DS_Store files from Mac in the .gitignore.

This has been done using the last revision of Roo from source, the last test was made with the revision 9ba1451...

It works in Mac OS X Lion (10.7.2) 64 and Ubuntu 10.04 x64. There is a problem in Windows with the file coursemgr-ch07-webflow_2011-10-16_20:04:17.zip from the chapter 07 and I can't clone the repository for now.

For debugging if necessary, STS 2.8.0 has been used.

In the chapter 4 was necessary to modify the database.properties (to provide database username and password) and persistence.xml (to create the database), but this changes won't be included.

I hope this helps you.

### CODE REVIEW

**Comment by krimple** [comment]
Javier, I looked at these and I think I've done the same things. Unfortunately I got a blind curve with the updates in various snapshots.  I'm going to review the content in your changes - especially chapter 6.

**Comment by jbbarquero** [comment]
Thank you very much for your response.

I was very busy since the last update and I couldn't follow the code as I wished.

There's nothing special in the changes. I only opened the code with the last development version of Roo and I tried to make them compile and to pass the tests too.

If I'm not wrong, Roo didn't delete the _Roo_Entity aspects and they conflict with the new _Roo_jpa\* (I don't remember now the exact name) This was the main issue.

I think that it should better to use the RC1 that has been released today.

Now I'd like to use the code of the addons chapters, because my main goal is to easyly include jquery in Roo.

I want a simple project, because at work we have had a lot of problems with a medium project that has entities with composite primary keys, entities in external jars, jquery using Ajax (a lot of problems come with the  Jackson converter [why we use Jackson and Jquery instead of Flexjson and dojo? Sincerly, I can't remember)

Besides, I still don't know enough JQuery for some tasks.

I appreciate a lot your email.

Greetings.

**Comment by krimple** [comment]
Sure, Javier,

If I'm not wrong, Roo didn't delete the _Roo_Entity aspects and they

> conflict with the new _Roo_jpa\* (I don't remember now the exact name) This
> was the main issue.

Right.  It was ug-ly!  It took me a while there.  I'm planning on not
including the .aj files in the repo so that you won't get this problem.

> I think that it should better to use the RC1 that has been released today.
> 
> I've been doing the updates this weekend.  My code samples are still a
> mess.  I'm working through them, however.  I've added a wiki page to GitHub
> and will be updating it as I do conversions.  I'm up to chapter 5.  I've
> done some significant updates that will make it to the MEAP at some point
> including adding info on multi-module Roo and roo repositories and services.
> 
> Now I'd like to use the code of the addons chapters, because my main goal
> is to easyly include jquery in Roo.
> 
> That code works today against snapshot.  I'll convert it to RC1 but I don't
> think anything will change, as I just cleaned it up last week. See if you
> can just change the roo.version in the POM.
> 
> I want a simple project, because at work we have had a lot of problems
> with a medium project that has entities with composite primary keys,
> entities in external jars, jquery using Ajax (a lot of problems come with
> the  Jackson converter [why we use Jackson and Jquery instead of Flexjson
> and dojo? Sincerly, I can't remember)
> 
> LOL aren't all project decisions made in an imperfect world?
> 
> Besides, I still don't know enough JQuery for some tasks

$().select("I have no idea").("isn't this perl in javascript form?").blink()

:)

**Comment by krimple** [comment]
Ok, I've moved further but used your information as a big help.  Thanks, and now that things are getting more stable, I think I can actually take some pull requests, at least once a given example goes "live" - see the wiki page for details.

**Comment by jbbarquero** [comment]
It's a pleasure and an honor to participate on the project.

Regarding not including the aspect files (.aj) I disagree if you don't mind that I give you my opinion.

The java spring project isn't complete without the aspect files and it won't work without opening the Roo shell. For instance, maven won't succeed 

I expect that Roo will manage the deprecated annotations (I haven't tested the new RC yet)

I think it would be a good idea to include the Roo script in each project (I'm used to renaming and clean the log.roo file, and then I add the new file, script.roo for instance, to the repository)

**Pull request closed without merging**
